spring.application.name=nestora_app
# ================================
# SERVER
# ================================
server.port=8080

# ================================
# DATABASE ? my db password
# ================================
spring.datasource.url=jdbc:mysql://localhost:3306/nestora_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=rahman__12181
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ================================
# JPA / HIBERNATE
# ================================
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ================================
# JWT
# ================================
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.access-token.expiry=900000
jwt.refresh-token.expiry=604800000

# ================================
# CLOUDINARY ? images/videos
# ================================
cloudinary.cloud-name=dhw16mrqc
cloudinary.api-key=516456681872571
cloudinary.api-secret=Bhwww_d4AKCyev5G81ST_2hrRFg

spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB

# ================================
# APP
# ================================
# ================================
# EMAIL ? Gmail SMTP
# ================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lutfur1218@gmail.com
spring.mail.password=oxahknwxdphwggik
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# OTP expiry minutes
otp.expiry.minutes=10
server.address=0.0.0.0
spring.security.enabled=false
# Firebase
firebase.credentials.path=firebase-credentials.json
# Razorpay
razorpay.key.id=rzp_test_SoxdG3vJAQUSQG
razorpay.key.secret=K1ggr9cfw4FWsJwJuKKNFH17
# MSG91 SMS
msg91.auth.key=515528ARfJJEsRcbwE6a00c852P1
msg91.template.id=6a00cb8958e4b5eb7a020383
msg91.sender.id=NESTORA
# Scheduler
spring.task.scheduling.enabled=true
# Request size limits

# Actuator ? sirf health expose karo
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# Error details hide karo
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-exception=false

# Session disabled (already stateless)
spring.session.store-type=none

# Hibernate SQL print band karo production me
spring.jpa.hibernate.ddl-auto=update